---
groups:
- name: deployment-pipeline
  jobs: 
    - build-todos-api
    - deploy-todos-api



resource_types:

- name: slack-alert
  type: docker-image
  source:
    repository: arbourd/concourse-slack-alert-resource

resources:

- name: notify
  type: slack-alert
  icon: slack
  source:
    url: ((slack_webhook))

- name: todos-apps-master
  type: git
  icon: github-circle
  source:
    uri: git@github.com:Pivotal-Field-Engineering/todos-apps
    branch: master

jobs:
- name: job-build
  serial: true
  plan:
  - get: resource-concourse
  - get: resource-unit
  - get: resource-version
    trigger: true  
  - task: task-detect
    file: resource-concourse/ci/detect-unit.yml    
  - task: task-build
    file: resource-concourse/ci/build-maven.yml
  - task: task-release
    params:
      BUILD_NAME: {{build_name}}
    file: resource-concourse/ci/release-static.yml  
  - put: resource-release-unit
    params:
      name: resource-release/release-name
      tag: resource-release/release-tag
      body: resource-release/release-body
      globs:
      - resource-release/*.tar