---
resources:
- name: resource-concourse
  type: git
  source:
    uri: {{resource_concourse_uri}}
    branch: {{resource_concourse_branch}}    
- name: resource-version
  type: semver
  source:
    driver: git
    uri: {{resource_version_uri}}
    branch: {{resource_version_branch}}
    file: version
    private_key: {{private-key-github}}     
- name: resource-source-code
  type: git
  source:
    uri: {{resource_source_code_uri}}
    branch: {{resource_source_code_branch}}
    private_key: {{private-key-github}}   
- name: resource-release
  type: github-release
  source:
    owner: {{resource_release_owner}}
    repository: {{resource_release_repository}}
    access_token: {{private-token-github}}    
jobs:
- name: job-release
  plan:
  - get: resource-concourse
  - get: resource-source-code
    trigger: true
  - task: task-build
    file: resource-concourse/ci/detect.yml    
  - get: resource-version
    params: {bump: {{resource_version_bump}}, pre: {{resource_version_pre}}}
  - task: task-build
    file: resource-concourse/ci/build.yml
  - task: task-release
    file: resource-concourse/ci/release.yml    
  - put: resource-version
    params: {file: resource-version/version}
  - put: resource-release
    params:
      name: resource-release-output/release-name
      tag: resource-release-output/release-tag
      body: resource-release-output/release-body
      globs:
      - resource-build-output/target/*.jar    


