---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk-alpine'

inputs:
  - name: resource-source-code
  - name: resource-kit
  - name: resource-version

outputs:
  - name: resource-build-output

run:
  path: resource-kit/ci/build.sh        